version: '3.8'
services:
  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 0000
      POSTGRES_DB: phonebook_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    image: ${DOCKERHUB_USERNAME}/phonebook:latest
    container_name: spring_app
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/phonebook_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 0000
      JWT_SECRET: ${JWT_SECRET_KEY}
    ports:
      - "8080:8080"
    volumes:
      - ./logs:/app/logs

  frontend:
    image: asanovbekzod/frontend:latest
    container_name: frontend
    depends_on:
      - app
    ports:
      - "80:80"

volumes:
  postgres_data:
